"""initial schema

Revision ID: 33a0b8e8aad9
Revises:
Create Date: 2026-05-24 21:42:31.860774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import MEDIUMTEXT

revision = '33a0b8e8aad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # rooms created first (without closed_proof_id FK) to break circular dependency
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem', sa.Text().with_variant(MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed_consensus', 'closed_capped', 'closed_manual', name='room_status'), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('closed_proof_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('producer', 'reviewer', name='participant_role'), nullable=False),
    sa.Column('token', sa.String(length=43).with_variant(sa.dialects.mysql.CHAR(43), 'mysql'), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('first_post_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'name', name='uq_room_name'),
    sa.UniqueConstraint('token', name='uq_token')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('proof', 'revision', 'comment', 'agree', name='post_type'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text().with_variant(MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent', 'posts', ['parent_id'], unique=False)
    op.create_index('idx_room_created', 'posts', ['room_id', 'created_at'], unique=False)
    op.create_index('idx_room_type', 'posts', ['room_id', 'type'], unique=False)
    op.create_table('reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participant_post', 'reads', ['participant_id', 'post_id'], unique=False)
    op.create_index('idx_post', 'reads', ['post_id'], unique=False)
    # Add closed_proof_id FK after posts table exists (circular FK resolution)
    # Use batch mode for SQLite compatibility (SQLite does not support ADD CONSTRAINT)
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_rooms_closed_proof", "posts", ["closed_proof_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop closed_proof_id FK before dropping posts (circular FK resolution)
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint("fk_rooms_closed_proof", type_="foreignkey")
    op.drop_index('idx_post', table_name='reads')
    op.drop_index('idx_participant_post', table_name='reads')
    op.drop_table('reads')
    op.drop_index('idx_room_type', table_name='posts')
    op.drop_index('idx_room_created', table_name='posts')
    op.drop_index('idx_parent', table_name='posts')
    op.drop_table('posts')
    op.drop_table('participants')
    op.drop_table('rooms')
    # ### end Alembic commands ###
